apiVersion: v1
kind: Service
metadata:
  namespace: eshop
  name: portfolio-rest-api
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: portfolio-rest-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: eshop
  name: portfolio-rest-api-deployment
  labels:
    app: portfolio-rest-api
spec:
  selector:
    matchLabels:
      app: portfolio-rest-api
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: portfolio-rest-api
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsUser: 1001
        runAsGroup: 0
        fsGroup: 0
      containers:
        - name: eshop
          image: maxmorev/portfolio-rest-api:latest
          volumeMounts:
            - name: h2-storage
              mountPath: /opt/micro/h2
          ports:
            - containerPort: 8080
              name: quarkus
          resources:
            requests:
              memory: "256Mi"
              cpu: "256m" # 1/4 core
            limits:
              memory: "512Mi"
              cpu: "500m" # 1/2 core
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 12
            timeoutSeconds: 5
            periodSeconds: 3
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 8
            failureThreshold: 1
      volumes:
        - name: h2-storage
          persistentVolumeClaim:
            claimName: pvc-portfolio