apiVersion: v1
kind: Namespace
metadata:
  name: eshop
  labels:
    app.kubernetes.io/name: eshop
    app.kubernetes.io/instance: eshop

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: eshop
  name: pvc-portfolio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Gi