quarkus:
  smallrye-openapi:
    path: swagger
  swagger-ui:
    always-include: true

  datasource:
    db-kind: H2
    username: sarah
    password: connor
    jdbc:
      url: jdbc:h2:file:/opt/micro/h2/portfolio;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;MODE=PostgreSQL;INIT=RUNSCRIPT FROM 'classpath:sql/initial.sql';
  hibernate-orm:
    database:
      generation: none
      default-schema: PORTFOLIO
  liquibase:
    migrate-at-start: true
    change-log: db/changeLog.xml
    default-schema-name: PORTFOLIO
