quarkus:
  smallrye-openapi:
    path: swagger
  swagger-ui:
    always-include: true

  datasource:
    db-kind: H2
    username: sarah
    password: connor
    jdbc:
      url: jdbc:h2:file:/opt/micro/h2/portfolio;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;MODE=PostgreSQL;INIT=CREATE SCHEMA IF NOT EXISTS "portfolio";
  hibernate-orm:
    database:
      generation: update

