package ru.max0l0gy.eshop.entity;

public interface Constants {

    String ID_GENERATOR_PORTFOLIO = "ID_GENERATOR_PORTFOLIO";
    String ID_GENERATOR_PORTFOLIO_IMAGE = "ID_GENERATOR_PORTFOLIO_IMAGE";
    String ID_GENERATOR_PORTFOLIO_SEQUENCE_NAME = "SEQUENCE_PORTFOLIO";
    String ID_GENERATOR_PORTFOLIO_IMAGE_SEQUENCE_NAME = "SEQUENCE_PORTFOLIO_IMAGE";

}
